apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-api
  namespace: rps
  labels:
    app: challenge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-api
  template:
    metadata:
      labels:
        app: challenge-api
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: challenge-api
          image: ghcr.io/dgkim-lab/kube-hello-kiali-challenge-api:46f6aba59d4142ea9d23bfa3126bf7329a997d99
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: JUDGE_API_URL
              value: http://judge-api:8081
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
