apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-api
  namespace: kube-hello-kiali
  labels:
    app: judge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-api
  template:
    metadata:
      labels:
        app: judge-api
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: judge-api
          image: ghcr.io/dgkim-lab/kube-hello-kiali-judge-api:46f6aba59d4142ea9d23bfa3126bf7329a997d99
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
