apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-api
  namespace: rps
  labels:
    app: judge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-api
  template:
    metadata:
      labels:
        app: judge-api
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: judge-api
          image: ghcr.io/dgkim-lab/kube-hello-kiali-judge-api:198ae3406a5aa897f58403d1c0c047e3d33015f4
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: ERROR_RATE
              value: "0.2"
            - name: OTEL_SERVICE_NAME
              value: judge-api
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger.jaeger:4318
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
