apiVersion: v1
kind: Service
metadata:
  name: judge-api
  namespace: rps
  labels:
    app: judge-api
spec:
  selector:
    app: judge-api
  ports:
    - name: http
      port: 8081
      targetPort: 8081

