apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-hello-kiali
  namespace: argocd
spec:
  project: kube-hello-kiali
  source:
    repoURL: https://github.com/dgkim-lab/kube-hello-kiali.git
    targetRevision: main
    path: deploy
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: rps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
